name: Job URL Printer
author: mmatheson
description: Prints the URL to the current job

runs:
  using: composite
  steps:
    - name: Print
      run: |
          jobs=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs)
          job_url=$(echo $jobs | jq -r '.jobs[] | .html_url')
          job_id=$(echo $jobs | jq -r '.jobs[] | .id')
          echo Job URL: $job_url
      shell: bash
