name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # users will have to specify the correct permissions here
    permissions:
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Job
        uses: ./.github/actions/job_url
        
        # Users will also need to specify the GH_TOKEN here
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

